/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple.inventory.reservation.system;

import simple.inventory.reservation.system.DB.CLASS_ACCOUNTS;
import simple.inventory.reservation.system.DB.DAO_ACCOUNTS;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import simple.inventory.reservation.system.DB.CLASS_TRANSACTIONS;
import simple.inventory.reservation.system.DB.DAO_TRANSACTIONS;

/**
 *
 * @author dzhon
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        
    }
    
    public ADMIN(int currID, String currUSER) {
        initComponents();
        setDate();
        // COMPONENTS 
        btnVIEWACC.setOpaque(true);
        btnADD.setOpaque(true);
        btnUPDATE.setOpaque(true);
        btnDELETE.setOpaque(true);
        btnSIGNOUT.setOpaque(true);
        btnACTION.setOpaque(true);
        btnVIEWTRANS.setOpaque(true);
        
        lblUSER.setText("Welcome, "+currUSER);
        resetState();
        btnVIEWACC.doClick();
        
    }
    
    public DAO_ACCOUNTS daoACCOUNTS = new DAO_ACCOUNTS();
    public DAO_TRANSACTIONS daoTRANSACTIONS = new DAO_TRANSACTIONS();
    public CLASS_ACCOUNTS tempAccount = null;
    
    public int newID = 0;
    public int selectedID = 0 ;
    public String selectedUSER = "";
    public String selectedPASS = "";
    public String selectedPERSONID = "";
    public String selectedFNAME = "";
    public String selectedLNAME = "";
    public int selectedROLE = 19;

    
    public void resetState() {
        loadALLACCOUNTS();
        loadALLTRANSACTIONS();
        btnUPDATE.setEnabled(false);
        btnDELETE.setEnabled(false);
        selectedID = 0 ;
        selectedUSER = "";
        selectedPASS = "";
        selectedPERSONID = "";
        selectedFNAME = "";
        selectedLNAME = "";
        selectedROLE = 19;
         
        txtUSERNAME.setText("");
        txtPASSWORD.setText("");
        txtFNAME.setText("");
        txtLNAME.setText("");
        txtPERSONID.setText("");
        cbROLE.setSelectedIndex(0);
        cbROLE.setVisible(true);
    }
    
    public void loadALLACCOUNTS(){
        List<CLASS_ACCOUNTS> accounts = null;
        accounts = daoACCOUNTS.getAllAccounts();
        TableModelACCOUNTS model = new TableModelACCOUNTS(accounts);
        tblACCOUNTS.setModel(model);
        
        newID = accounts.get(accounts.size()-1).getId() + 1;
    }
    
    public void loadALLTRANSACTIONS(){
        List<CLASS_TRANSACTIONS> transactions = null;
        transactions = daoTRANSACTIONS.getAllTransactions();
        TableModelTRANSACTIONS model = new TableModelTRANSACTIONS(transactions);
        tblTRANS.setModel(model);
    }
    
    public void setDate(){
        Timer timer = new Timer(1000, new setDateActionListener());
        timer.start();
    }
    class setDateActionListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            String currDate = new SimpleDateFormat("dd-MM-yyyy  |  HH:mm:ss").format(Calendar.getInstance().getTime());      
            lblTIME.setText(currDate);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLEFT = new javax.swing.JPanel();
        lblLOGO1 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        lblUSER = new javax.swing.JLabel();
        lblTIME = new javax.swing.JLabel();
        btnUPDATE = new javax.swing.JButton();
        btnDELETE = new javax.swing.JButton();
        btnSIGNOUT = new javax.swing.JButton();
        btnVIEWACC = new javax.swing.JButton();
        btnVIEWTRANS = new javax.swing.JButton();
        panelRIGHTVIEWACC = new javax.swing.JPanel();
        lblTITLE5 = new javax.swing.JLabel();
        lblLOGO3 = new javax.swing.JLabel();
        lblTITLE6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblACCOUNTS = new javax.swing.JTable();
        lblTITLE7 = new javax.swing.JLabel();
        panelRIGHTCRUD = new javax.swing.JPanel();
        lblACTION6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblACTION1 = new javax.swing.JLabel();
        txtUSERNAME = new javax.swing.JTextField();
        lblACTION2 = new javax.swing.JLabel();
        txtPASSWORD = new javax.swing.JPasswordField();
        txtPERSONID = new javax.swing.JTextField();
        lblACTION3 = new javax.swing.JLabel();
        txtFNAME = new javax.swing.JTextField();
        lblACTION4 = new javax.swing.JLabel();
        lblACTION5 = new javax.swing.JLabel();
        txtLNAME = new javax.swing.JTextField();
        cbROLE = new javax.swing.JComboBox<>();
        lblACTION7 = new javax.swing.JLabel();
        btnACTION = new javax.swing.JButton();
        lblTITLE3 = new javax.swing.JLabel();
        lblLOGO2 = new javax.swing.JLabel();
        lblTITLE4 = new javax.swing.JLabel();
        panelRIGHTVIEWTRANS = new javax.swing.JPanel();
        lblTITLE8 = new javax.swing.JLabel();
        lblLOGO4 = new javax.swing.JLabel();
        lblTITLE9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTRANS = new javax.swing.JTable();
        lblTITLE10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMIN");
        setBackground(new java.awt.Color(0, 128, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        panelLEFT.setBackground(new java.awt.Color(0, 128, 50));

        lblLOGO1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblLOGO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLOGO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/educator-ok.png"))); // NOI18N
        lblLOGO1.setName("lblTITLE"); // NOI18N

        btnADD.setBackground(new java.awt.Color(0, 128, 50));
        btnADD.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnADD.setForeground(new java.awt.Color(255, 255, 255));
        btnADD.setText("ADD ACCOUNT  ");
        btnADD.setBorder(null);
        btnADD.setBorderPainted(false);
        btnADD.setContentAreaFilled(false);
        btnADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADD.setFocusPainted(false);
        btnADD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnADD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnADDMouseExited(evt);
            }
        });
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        lblUSER.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblUSER.setForeground(new java.awt.Color(255, 255, 255));
        lblUSER.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUSER.setText("WELCOME, BLABLA");

        lblTIME.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblTIME.setForeground(new java.awt.Color(255, 255, 255));
        lblTIME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTIME.setText("TIME");

        btnUPDATE.setBackground(new java.awt.Color(0, 128, 50));
        btnUPDATE.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnUPDATE.setForeground(new java.awt.Color(255, 255, 255));
        btnUPDATE.setText("UPDATE ACCOUNT  ");
        btnUPDATE.setBorder(null);
        btnUPDATE.setBorderPainted(false);
        btnUPDATE.setContentAreaFilled(false);
        btnUPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATE.setFocusPainted(false);
        btnUPDATE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUPDATE.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUPDATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUPDATEMouseExited(evt);
            }
        });
        btnUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEActionPerformed(evt);
            }
        });

        btnDELETE.setBackground(new java.awt.Color(0, 128, 50));
        btnDELETE.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnDELETE.setForeground(new java.awt.Color(255, 255, 255));
        btnDELETE.setText("DELETE ACCOUNT  ");
        btnDELETE.setBorder(null);
        btnDELETE.setBorderPainted(false);
        btnDELETE.setContentAreaFilled(false);
        btnDELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETE.setFocusPainted(false);
        btnDELETE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDELETE.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDELETEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDELETEMouseExited(evt);
            }
        });
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });

        btnSIGNOUT.setBackground(new java.awt.Color(0, 128, 50));
        btnSIGNOUT.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSIGNOUT.setForeground(new java.awt.Color(255, 255, 255));
        btnSIGNOUT.setText("LOG OUT  ");
        btnSIGNOUT.setActionCommand("");
        btnSIGNOUT.setBorder(null);
        btnSIGNOUT.setBorderPainted(false);
        btnSIGNOUT.setContentAreaFilled(false);
        btnSIGNOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSIGNOUT.setFocusPainted(false);
        btnSIGNOUT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSIGNOUT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSIGNOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSIGNOUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSIGNOUTMouseExited(evt);
            }
        });
        btnSIGNOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIGNOUTActionPerformed(evt);
            }
        });

        btnVIEWACC.setBackground(new java.awt.Color(0, 128, 50));
        btnVIEWACC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnVIEWACC.setForeground(new java.awt.Color(255, 255, 255));
        btnVIEWACC.setText("VIEW ACCOUNTS  ");
        btnVIEWACC.setActionCommand("");
        btnVIEWACC.setBorder(null);
        btnVIEWACC.setBorderPainted(false);
        btnVIEWACC.setContentAreaFilled(false);
        btnVIEWACC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVIEWACC.setFocusPainted(false);
        btnVIEWACC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVIEWACC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVIEWACC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVIEWACCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVIEWACCMouseExited(evt);
            }
        });
        btnVIEWACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIEWACCActionPerformed(evt);
            }
        });

        btnVIEWTRANS.setBackground(new java.awt.Color(0, 128, 50));
        btnVIEWTRANS.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnVIEWTRANS.setForeground(new java.awt.Color(255, 255, 255));
        btnVIEWTRANS.setText("VIEW TRANSACTIONS  ");
        btnVIEWTRANS.setBorder(null);
        btnVIEWTRANS.setBorderPainted(false);
        btnVIEWTRANS.setContentAreaFilled(false);
        btnVIEWTRANS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVIEWTRANS.setFocusPainted(false);
        btnVIEWTRANS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVIEWTRANS.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVIEWTRANS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVIEWTRANSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVIEWTRANSMouseExited(evt);
            }
        });
        btnVIEWTRANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIEWTRANSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLEFTLayout = new javax.swing.GroupLayout(panelLEFT);
        panelLEFT.setLayout(panelLEFTLayout);
        panelLEFTLayout.setHorizontalGroup(
            panelLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLEFTLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblLOGO1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(btnADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLEFTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUSER, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTIME, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(btnUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSIGNOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVIEWACC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVIEWTRANS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLEFTLayout.setVerticalGroup(
            panelLEFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLEFTLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLOGO1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUSER)
                .addGap(5, 5, 5)
                .addComponent(lblTIME)
                .addGap(59, 59, 59)
                .addComponent(btnVIEWACC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVIEWTRANS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSIGNOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        getContentPane().add(panelLEFT);
        panelLEFT.setBounds(0, 0, 225, 600);

        panelRIGHTVIEWACC.setBackground(new java.awt.Color(251, 197, 49));
        panelRIGHTVIEWACC.setPreferredSize(new java.awt.Dimension(575, 600));
        panelRIGHTVIEWACC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTITLE5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE5.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE5.setText("ACCOUNTS");
        lblTITLE5.setName(""); // NOI18N
        panelRIGHTVIEWACC.add(lblTITLE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblLOGO3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblLOGO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLOGO3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seal-ok.png"))); // NOI18N
        lblLOGO3.setName("lblTITLE"); // NOI18N
        panelRIGHTVIEWACC.add(lblLOGO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblTITLE6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE6.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE6.setText("RESERVATION SYSTEM");
        lblTITLE6.setName(""); // NOI18N
        panelRIGHTVIEWACC.add(lblTITLE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        tblACCOUNTS.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tblACCOUNTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USERNAME", "PASSWORD", "PERSON_ID", "FNAME", "LNAME", "ROLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblACCOUNTS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblACCOUNTSMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblACCOUNTS);
        if (tblACCOUNTS.getColumnModel().getColumnCount() > 0) {
            tblACCOUNTS.getColumnModel().getColumn(0).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(0).setPreferredWidth(35);
            tblACCOUNTS.getColumnModel().getColumn(0).setHeaderValue("ID");
            tblACCOUNTS.getColumnModel().getColumn(1).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(1).setHeaderValue("USERNAME");
            tblACCOUNTS.getColumnModel().getColumn(2).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(2).setHeaderValue("PASSWORD");
            tblACCOUNTS.getColumnModel().getColumn(3).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(3).setHeaderValue("PERSON_ID");
            tblACCOUNTS.getColumnModel().getColumn(4).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(4).setHeaderValue("FNAME");
            tblACCOUNTS.getColumnModel().getColumn(5).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(5).setHeaderValue("LNAME");
            tblACCOUNTS.getColumnModel().getColumn(6).setResizable(false);
            tblACCOUNTS.getColumnModel().getColumn(6).setHeaderValue("ROLE");
        }

        panelRIGHTVIEWACC.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 257, 570, 340));

        lblTITLE7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE7.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE7.setText("FEU TECH");
        lblTITLE7.setName(""); // NOI18N
        panelRIGHTVIEWACC.add(lblTITLE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        getContentPane().add(panelRIGHTVIEWACC);
        panelRIGHTVIEWACC.setBounds(225, 0, 575, 600);

        panelRIGHTCRUD.setBackground(new java.awt.Color(251, 197, 49));
        panelRIGHTCRUD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblACTION6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION6.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION6.setText("ID");
        lblACTION6.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 128, 50));
        txtID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID.setFocusable(false);
        txtID.setName("txtID"); // NOI18N
        panelRIGHTCRUD.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 245, -1));

        lblACTION1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION1.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION1.setText("USERNAME");
        lblACTION1.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        txtUSERNAME.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtUSERNAME.setForeground(new java.awt.Color(0, 128, 50));
        txtUSERNAME.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUSERNAME.setName("txtUSERNAME"); // NOI18N
        panelRIGHTCRUD.add(txtUSERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 245, -1));

        lblACTION2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION2.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION2.setText("PASSWORD");
        lblACTION2.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        txtPASSWORD.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtPASSWORD.setForeground(new java.awt.Color(0, 128, 50));
        txtPASSWORD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelRIGHTCRUD.add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 245, 30));

        txtPERSONID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtPERSONID.setForeground(new java.awt.Color(0, 128, 50));
        txtPERSONID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPERSONID.setName("txtUSERNAME"); // NOI18N
        panelRIGHTCRUD.add(txtPERSONID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 245, -1));

        lblACTION3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION3.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION3.setText("FACULTY/STAFF ID");
        lblACTION3.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        txtFNAME.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtFNAME.setForeground(new java.awt.Color(0, 128, 50));
        txtFNAME.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFNAME.setName("txtUSERNAME"); // NOI18N
        panelRIGHTCRUD.add(txtFNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 245, -1));

        lblACTION4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION4.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION4.setText("FIRST NAME");
        lblACTION4.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        lblACTION5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION5.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION5.setText("LAST NAME");
        lblACTION5.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        txtLNAME.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtLNAME.setForeground(new java.awt.Color(0, 128, 50));
        txtLNAME.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLNAME.setName("txtUSERNAME"); // NOI18N
        panelRIGHTCRUD.add(txtLNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 245, -1));

        cbROLE.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        cbROLE.setForeground(new java.awt.Color(0, 128, 50));
        cbROLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STAFF", "FACULTY" }));
        cbROLE.setBorder(null);
        cbROLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbROLE.setLightWeightPopupEnabled(false);
        panelRIGHTCRUD.add(cbROLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 245, -1));

        lblACTION7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lblACTION7.setForeground(new java.awt.Color(0, 128, 50));
        lblACTION7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblACTION7.setText("ROLE");
        lblACTION7.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblACTION7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        btnACTION.setBackground(new java.awt.Color(251, 197, 49));
        btnACTION.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnACTION.setForeground(new java.awt.Color(0, 128, 50));
        btnACTION.setBorder(null);
        btnACTION.setBorderPainted(false);
        btnACTION.setContentAreaFilled(false);
        btnACTION.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnACTION.setFocusPainted(false);
        btnACTION.setLabel("ADD ACCOUNT");
        btnACTION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnACTIONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnACTIONMouseExited(evt);
            }
        });
        btnACTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACTIONActionPerformed(evt);
            }
        });
        panelRIGHTCRUD.add(btnACTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 575, 35));

        lblTITLE3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE3.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE3.setText("RESERVATION SYSTEM");
        lblTITLE3.setName(""); // NOI18N
        panelRIGHTCRUD.add(lblTITLE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblLOGO2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblLOGO2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLOGO2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seal-ok.png"))); // NOI18N
        lblLOGO2.setName("lblTITLE"); // NOI18N
        panelRIGHTCRUD.add(lblLOGO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblTITLE4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE4.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE4.setText("FEU TECH");
        lblTITLE4.setName(""); // NOI18N
        panelRIGHTCRUD.add(lblTITLE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        getContentPane().add(panelRIGHTCRUD);
        panelRIGHTCRUD.setBounds(225, 0, 575, 600);

        panelRIGHTVIEWTRANS.setBackground(new java.awt.Color(251, 197, 49));
        panelRIGHTVIEWTRANS.setPreferredSize(new java.awt.Dimension(575, 600));
        panelRIGHTVIEWTRANS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTITLE8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE8.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE8.setText("TRANSACTIONS");
        lblTITLE8.setName(""); // NOI18N
        panelRIGHTVIEWTRANS.add(lblTITLE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblLOGO4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblLOGO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLOGO4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/seal-ok.png"))); // NOI18N
        lblLOGO4.setName("lblTITLE"); // NOI18N
        panelRIGHTVIEWTRANS.add(lblLOGO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblTITLE9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE9.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE9.setText("RESERVATION SYSTEM");
        lblTITLE9.setName(""); // NOI18N
        panelRIGHTVIEWTRANS.add(lblTITLE9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        tblTRANS.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tblTRANS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "U_ID", "B_ID", "B_FNAME", "B_LNAME", "ITEM_ID", "STATUS", "DATE_RES", "DATE_UPDATED"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblTRANS);
        if (tblTRANS.getColumnModel().getColumnCount() > 0) {
            tblTRANS.getColumnModel().getColumn(0).setResizable(false);
            tblTRANS.getColumnModel().getColumn(0).setPreferredWidth(35);
            tblTRANS.getColumnModel().getColumn(1).setResizable(false);
            tblTRANS.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblTRANS.getColumnModel().getColumn(2).setResizable(false);
            tblTRANS.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblTRANS.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        panelRIGHTVIEWTRANS.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 257, 570, 340));

        lblTITLE10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        lblTITLE10.setForeground(new java.awt.Color(0, 128, 50));
        lblTITLE10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE10.setText("FEU TECH");
        lblTITLE10.setName(""); // NOI18N
        panelRIGHTVIEWTRANS.add(lblTITLE10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        getContentPane().add(panelRIGHTVIEWTRANS);
        panelRIGHTVIEWTRANS.setBounds(225, 0, 575, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMouseEntered
        // TODO add your handling code here:
        btnADD.setBackground(new Color(251,197,49));
        btnADD.setForeground(new Color(0,128,50));
    }//GEN-LAST:event_btnADDMouseEntered

    private void btnADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADDMouseExited
        // TODO add your handling code here:

        btnADD.setBackground(new Color(0,128,50));
        btnADD.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnADDMouseExited

    private void btnUPDATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUPDATEMouseEntered
        // TODO add your handling code here:
        if(btnUPDATE.isEnabled() == true){
            btnUPDATE.setBackground(new Color(251,197,49));
            btnUPDATE.setForeground(new Color(0,128,50));
        }
    }//GEN-LAST:event_btnUPDATEMouseEntered

    private void btnUPDATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUPDATEMouseExited
        // TODO add your handling code here:
        btnUPDATE.setBackground(new Color(0,128,50));
        btnUPDATE.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnUPDATEMouseExited

    private void btnDELETEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDELETEMouseEntered
        // TODO add your handling code here:
        if(btnDELETE.isEnabled() == true) {
            btnDELETE.setBackground(new Color(251,197,49));
            btnDELETE.setForeground(new Color(0,128,50));
        }
    }//GEN-LAST:event_btnDELETEMouseEntered

    private void btnDELETEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDELETEMouseExited
        // TODO add your handling code here:
        btnDELETE.setBackground(new Color(0,128,50));
        btnDELETE.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDELETEMouseExited

    private void btnSIGNOUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSIGNOUTMouseEntered
        // TODO add your handling code here:
        btnSIGNOUT.setBackground(new Color(251,197,49));
        btnSIGNOUT.setForeground(new Color(0,128,50));
    }//GEN-LAST:event_btnSIGNOUTMouseEntered

    private void btnSIGNOUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSIGNOUTMouseExited
        // TODO add your handling code here:
        btnSIGNOUT.setBackground(new Color(0,128,50));
        btnSIGNOUT.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSIGNOUTMouseExited

    private void btnACTIONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnACTIONMouseEntered
        // TODO add your handling code here:
        btnACTION.setBackground(new Color(0,128,50));
        btnACTION.setForeground(new Color(251,197,49));
    }//GEN-LAST:event_btnACTIONMouseEntered

    private void btnACTIONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnACTIONMouseExited
        // TODO add your handling code here:                                    
        // TODO add your handling code here:
        btnACTION.setBackground(new Color(251,197,49));
        btnACTION.setForeground(new Color(0,128,50));
    }//GEN-LAST:event_btnACTIONMouseExited

    private void btnVIEWACCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVIEWACCMouseEntered
        // TODO add your handling code here:
        btnVIEWACC.setBackground(new Color(251,197,49));
        btnVIEWACC.setForeground(new Color(0,128,50));
    }//GEN-LAST:event_btnVIEWACCMouseEntered

    private void btnVIEWACCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVIEWACCMouseExited
        // TODO add your handling code here:
        btnVIEWACC.setBackground(new Color(0,128,50));
        btnVIEWACC.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVIEWACCMouseExited

    private void btnVIEWTRANSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVIEWTRANSMouseEntered
        // TODO add your handling code here:
        btnVIEWTRANS.setBackground(new Color(251,197,49));
        btnVIEWTRANS.setForeground(new Color(0,128,50));
    }//GEN-LAST:event_btnVIEWTRANSMouseEntered

    private void btnVIEWTRANSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVIEWTRANSMouseExited
        // TODO add your handling code here:
        btnVIEWTRANS.setBackground(new Color(0,128,50));
        btnVIEWTRANS.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnVIEWTRANSMouseExited

    private void btnSIGNOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIGNOUTActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        this.hide();
        LOGIN loginForm = new LOGIN();
        loginForm.setVisible(true);
    }//GEN-LAST:event_btnSIGNOUTActionPerformed

    private void btnVIEWACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIEWACCActionPerformed
        // TODO add your handling code here:
        panelRIGHTVIEWACC.setVisible(true);
        panelRIGHTCRUD.setVisible(false);
        panelRIGHTVIEWTRANS.setVisible(false);
        
        loadALLACCOUNTS();
    }//GEN-LAST:event_btnVIEWACCActionPerformed

    private void btnVIEWTRANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIEWTRANSActionPerformed

        panelRIGHTVIEWACC.setVisible(false);
        panelRIGHTCRUD.setVisible(false);
        panelRIGHTVIEWTRANS.setVisible(true);
        
        loadALLTRANSACTIONS();
    }//GEN-LAST:event_btnVIEWTRANSActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        resetState();
        panelRIGHTVIEWACC.setVisible(false);
        panelRIGHTCRUD.setVisible(true);
        panelRIGHTVIEWTRANS.setVisible(false);
        
        btnACTION.setText("ADD ACCOUNT");
        txtID.setText(Integer.toString(newID));
    }//GEN-LAST:event_btnADDActionPerformed

    private void btnACTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACTIONActionPerformed
        // TODO add your handling code here:;
        int id = Integer.parseInt(txtID.getText()) ;
        String user = txtUSERNAME.getText();
        String pass = txtPASSWORD.getText();
        String personID = txtPERSONID.getText();
        String fname = txtFNAME.getText();
        String lname = txtLNAME.getText();
        int role = 0;
        if(selectedROLE == 0) {
            role = 0;
        }else{
            role = cbROLE.getSelectedIndex() + 1;
        }
        
        tempAccount = new CLASS_ACCOUNTS(id, user, pass, personID, fname, lname, role);
        if(btnACTION.getText() == "ADD ACCOUNT") {
            int Confirmation = JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE YOU WANT TO ADD NEW USER?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(Confirmation == 0) { 
                try {
                    daoACCOUNTS.addAccount(tempAccount);
                    resetState();
                    btnVIEWACC.doClick();
                } catch (SQLException ex) {
                    Logger.getLogger(ADMIN.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else if(btnACTION.getText() == "UPDATE ACCOUNT") {
            int Confirmation = JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE YOU WANT TO UPDATE USER?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(Confirmation == 0)  {
                try {
                    daoACCOUNTS.updateAccount(tempAccount);
                    resetState();
                    btnVIEWACC.doClick();
                } catch (SQLException ex) {
                    Logger.getLogger(ADMIN.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
        
    }//GEN-LAST:event_btnACTIONActionPerformed

    private void btnUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEActionPerformed
        // TODO add your handling code here:
        
        // PASS VALUE TO FORM
        txtID.setText(""+selectedID);
        txtUSERNAME.setText(selectedUSER);
        txtPASSWORD.setText(selectedPASS);
        txtPERSONID.setText(selectedPERSONID);
        txtFNAME.setText(selectedFNAME);
        txtLNAME.setText(selectedLNAME);
        if(selectedROLE == 0){
            cbROLE.setVisible(false);
        }else if (selectedROLE == 1) {
            cbROLE.setSelectedIndex(0);
            cbROLE.setVisible(true);
        }else{
            cbROLE.setSelectedIndex(1);
            cbROLE.setVisible(true);
        }
        
        panelRIGHTVIEWACC.setVisible(false);
        panelRIGHTCRUD.setVisible(true);
        panelRIGHTVIEWTRANS.setVisible(false);
        
        btnACTION.setText("UPDATE ACCOUNT");
        
    }//GEN-LAST:event_btnUPDATEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
        // TODO add your handling code here:
        tempAccount = new CLASS_ACCOUNTS(selectedID, selectedUSER, selectedPASS, selectedPERSONID, selectedFNAME, selectedLNAME, selectedROLE);
        int Confirmation = JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE YOU WANT TO DELETE USER WITH ID = " + selectedID + " AND USERNAME = "+ selectedUSER +"?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if(Confirmation == 0){   
            try {
                daoACCOUNTS.deleteAccount(tempAccount);
                resetState();
                btnVIEWACC.doClick();
            } catch (SQLException ex) {
                Logger.getLogger(ADMIN.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void tblACCOUNTSMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblACCOUNTSMouseReleased
        // TODO add your handling code here:
        // get selected account
        int row = tblACCOUNTS.getSelectedRow();
        // make sure a row is selected
        if(row < 0) {
            btnUPDATE.setEnabled(false);
            btnDELETE.setEnabled(false);
        }else{
            btnUPDATE.setEnabled(true);
            btnDELETE.setEnabled(true);
            
            // GET VALUE OF SELECTED ROW
            selectedID = Integer.parseInt(String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.ID_COL))) ;
            selectedUSER = String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.USERNAME_COL));
            selectedPASS = String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.PASSWORD_COL));
            selectedPERSONID = String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.PERSON_ID_COL));
            selectedFNAME = String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.FNAME_COL));
            selectedLNAME = String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.LNAME_COL));
            selectedROLE = Integer.parseInt(String.valueOf(tblACCOUNTS.getValueAt(row, TableModelACCOUNTS.ROLE_COL)));
            
        }
    }//GEN-LAST:event_tblACCOUNTSMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnACTION;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnSIGNOUT;
    private javax.swing.JButton btnUPDATE;
    private javax.swing.JButton btnVIEWACC;
    private javax.swing.JButton btnVIEWTRANS;
    private javax.swing.JComboBox<String> cbROLE;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblACTION1;
    private javax.swing.JLabel lblACTION2;
    private javax.swing.JLabel lblACTION3;
    private javax.swing.JLabel lblACTION4;
    private javax.swing.JLabel lblACTION5;
    private javax.swing.JLabel lblACTION6;
    private javax.swing.JLabel lblACTION7;
    private javax.swing.JLabel lblLOGO1;
    private javax.swing.JLabel lblLOGO2;
    private javax.swing.JLabel lblLOGO3;
    private javax.swing.JLabel lblLOGO4;
    private javax.swing.JLabel lblTIME;
    private javax.swing.JLabel lblTITLE10;
    private javax.swing.JLabel lblTITLE3;
    private javax.swing.JLabel lblTITLE4;
    private javax.swing.JLabel lblTITLE5;
    private javax.swing.JLabel lblTITLE6;
    private javax.swing.JLabel lblTITLE7;
    private javax.swing.JLabel lblTITLE8;
    private javax.swing.JLabel lblTITLE9;
    private javax.swing.JLabel lblUSER;
    private javax.swing.JPanel panelLEFT;
    private javax.swing.JPanel panelRIGHTCRUD;
    private javax.swing.JPanel panelRIGHTVIEWACC;
    private javax.swing.JPanel panelRIGHTVIEWTRANS;
    private javax.swing.JTable tblACCOUNTS;
    private javax.swing.JTable tblTRANS;
    private javax.swing.JTextField txtFNAME;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLNAME;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtPERSONID;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
